//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operaciones()
        {
            this.rol_operaciones = new HashSet<rol_operaciones>();
            this.rol_operaciones1 = new HashSet<rol_operaciones>();
            this.rol_operaciones2 = new HashSet<rol_operaciones>();
            this.rol_operaciones3 = new HashSet<rol_operaciones>();
        }
    
        public int id_operaciones { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_modulo { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual modulo modulo1 { get; set; }
        public virtual modulo modulo2 { get; set; }
        public virtual modulo modulo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_operaciones> rol_operaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_operaciones> rol_operaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_operaciones> rol_operaciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_operaciones> rol_operaciones3 { get; set; }
    }
}
