//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_operaciones
    {
        public int id_rol_operaciones { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_operacion { get; set; }
    
        public virtual operaciones operaciones { get; set; }
        public virtual operaciones operaciones1 { get; set; }
        public virtual operaciones operaciones2 { get; set; }
        public virtual operaciones operaciones3 { get; set; }
        public virtual rol rol { get; set; }
        public virtual rol rol1 { get; set; }
        public virtual rol rol2 { get; set; }
        public virtual rol rol3 { get; set; }
    }
}
