//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fecha { get; set; }
        public int id_rol { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual rol rol1 { get; set; }
        public virtual rol rol2 { get; set; }
        public virtual rol rol3 { get; set; }
    }
}
